version: 2

sources:
  - name: raw
    database: dbt-lewagon-project-486411
    schema: gz_raw_data
    loader: bigquery
    description: dataset gz_raw_data

    tables:
      - name: product
        identifier: raw_gz_product
        description: product greenweez

        columns:
          - name: products_id
            description: primary key

          - name: purchSE_PRICE
            description: purchase price

      - name: sales
        identifier: raw_gz_sales
        description: sales greenweez

        columns:
          - name: date_date
            description: date

          - name: orders_id
            description: order id

          - name: pdt_id
            description: product id

          - name: revenue
            description: revenue

          - name: quantity
            description: quantity

      - name: ship
        identifier: raw_gz_ship
        description: ship greenweez

        columns:
          - name: orders_id
            description: orders id

          - name: shipping_fee
            description: shipping fee

          - name: shipping_fee_1
            description: shipping fee 1

          - name: logCost
            description: log cost

          - name: ship_cost
            description: ship cost